name: Heighliner image build
description: Build and push Docker images with heighliner
author: bigs

inputs:
  github-token:
    description: "GitHub Token used to authenticate against a repository for Git context"
    default: ${{ github.token }}
    required: false

  heighliner-owner:
    description: "GitHub owner name of the heighliner repo to use"
    default: strangelove-ventures
    required: false

  heighliner-repo:
    description: "GitHub repo name of the heighliner repo to use"
    default: heighliner
    required: false

  clone-key:
    description: "base64 encoded ssh key used for authenticating a private repository"
    required: false

  heighliner-tag:
    description: "Name of the heighliner tag to use from GitHub (defaults to latest)"
    required: false

  chain:
    description: "Name of the chain (per chains.yaml) to build"
    required: true

  chains-spec-file:
    description: "Local path to chains.yaml file"
    required: false

  local:
    description: "Build image from local checked out repository (any non empty value is evaluated as true)"
    default: "false"
    required: false

  tag:
    description: "Resulting docker image tag (default derived from git ref)"
    required: false

  org:
    description: "GitHub organization override for building from a fork"
    required: false

  registry:
    description: "Docker container registry for pushing images"
    required: false
    default: ghcr.io/${{ github.repository_owner }}

  buildkit:
    description: "User docker buildkit for building images"
    required: false
    default: "true"

  build-dir:
    description: "Custom build directory, relative from root of repository"
    required: false

  buildkit-tag:
    description: "Name of the buildkit tag to use from GitHub (defaults to latest)"
    required: false

  buildkit-address:
    description: "Address of the buildkit socket, can be unix, tcp, ssl (default \"unix:///run/buildkit/buildkitd.sock\")"
    required: false
    default: tcp://127.0.0.1:8125

  platform:
    description: "Comma separated list of platforms to build containers for"
    required: false

  repo-host:
    description: "By default, this is 'github.com', but use this field to override. For example 'gitlab.com'."
    required: false

  github-organization:
    description: "The github owner (user/organization) of the chain source code."
    required: false
    default: ${{ github.repository_owner }}

  github-repo:
    description: "The github repository name of the chain source code."
    required: false
    default: ${{ github.event.repository.name }}

  git-ref:
    description: "Github short ref to build (branch, tag)"
    required: false
    default: ${{ github.ref_name }}

  dockerfile:
    description: "Which dockerfile strategy to use (folder names under dockerfile/). OPTIONS: cosmos, cargo, imported, or none. Use imported if you are importing an existing public docker image as a base for the heighliner image. Use none if you are not able to build the chain binary from source and need to download binaries into the image instead. Providing this option will override the default chains.yaml with a custom chain spec."
    required: false

  build-env:
    description: "Environment variables to be created during the build. Providing this option will override the default chains.yaml with a custom chain spec."
    required: false

  pre-build:
    description: "Any extra arguments needed to build the chain binary. Providing this option will override the default chains.yaml with a custom chain spec."
    required: false

  build-target:
    description: "The build command specific to the chosen dockerfile. For cosmos, likely make install. For cargo, likely build --release. Providing this option will override the default chains.yaml with a custom chain spec."
    required: false

  binaries:
    description: "The location of where the the build target places the binarie(s). Adding a ':' after the path allows for the ability to rename the binary. Providing this option will override the default chains.yaml with a custom chain spec."
    required: false

  libraries:
    description: "Any extra libraries need to run the binary. In addition to the binary itself, these will be copied over to the final image. Providing this option will override the default chains.yaml with a custom chain spec."
    required: false

  tar-export-path:
    description: "File path to export built image as docker tarball. This should end with a .tar extension (ex: docker-image.tar)"
    required: false
  
  skip:
    description: "Skip pushing images to registry"
    required: false
    default: "false"

  additional-args:
    description: "Additional arguments to pass to heighliner build command"
    required: false

outputs:
  imageid:
    description: "The docker image ID of the built image"

  digest:
    description: "The docker image digest of the built image"

  metadata:
    description: "The JSON metadata of the built image"

  tag:
    description: "The tag applied to the built image"

runs:
  using: 'node20'
  main: 'dist/index.js'
